"""
pages/site_index.py — machine-readable static endpoints.

  copy_machine_readable_assets() — copies registry files into _build/ and
                                    calls generate_site_index().
  generate_site_index()          — writes site-index.json.

Call copy_machine_readable_assets(build, cfg).
"""

from __future__ import annotations

import json
import shutil
from datetime import datetime, timezone
from pathlib import Path
from typing import Any

from config import (
    ANCHORS_YML,
    REFERENCES_JSON,
    ROOT_DIR,
    SITE_URL,
)


def _format_date(raw_date: Any) -> str | None:
    if not raw_date or len(str(raw_date)) != 6:
        return None
    s = str(raw_date)
    try:
        return f"20{s[0:2]}-{s[2:4]}-{s[4:6]}"
    except Exception:
        return None


def generate_site_index(
    build: Path,
    refs_data: dict[str, Any],
    anchor_map: dict[str, str],
    contents: dict[str, Any],
    link_map: dict[str, str],
) -> None:
    """
    Write site-index.json to build/.

    Single-fetch navigation index for tools, search, and LLMs.
    Merges paper metadata, section hierarchy, and anchor URLs.
    Omits editorial internals (outbound_ext_citation_ids, flag_ids, notes).
    """
    internal_papers = {
        p["shortcode"]: p
        for p in refs_data.get("internal_papers", [])
    }

    papers_out: list[dict[str, Any]] = []
    for shortcode, entry in contents.items():
        page = entry.get("page", f"{shortcode.lower()}.html")
        url  = f"{SITE_URL}/{page}"
        meta = internal_papers.get(shortcode, {})

        sections: list[dict[str, Any]] = []
        for key, title in entry.get("sections", {}).items():
            anchor_key = f"{shortcode}§{key}"
            anchor     = anchor_map.get(anchor_key, page)
            sections.append({
                "key":    str(key),
                "title":  title,
                "anchor": anchor,
                "url":    f"{SITE_URL}/{anchor}",
            })

        papers_out.append({
            "shortcode":         shortcode,
            "title":             entry.get("title", meta.get("title", shortcode)),
            "url":               url,
            "version":           meta.get("version", ""),
            "version_date":      _format_date(meta.get("version_date")) or "",
            "status":            meta.get("status", "active"),
            "outbound_internal": meta.get("outbound_internal", []),
            "inbound_internal":  meta.get("inbound_internal", []),
            "sections":          sections,
        })

    index = {
        "meta": {
            "generated":   datetime.now(tz=timezone.utc).strftime("%Y-%m-%dT%H:%M:%SZ"),
            "site":        SITE_URL,
            "papers":      len(papers_out),
            "anchors":     len(anchor_map),
            "description": (
                "Single-fetch navigation index for the Wealth Delta Tax research "
                "programme. Contains paper metadata, section hierarchy, and resolved "
                "anchor URLs. Generated by preprocess.py at each site build."
            ),
        },
        "papers":  papers_out,
        "anchors": anchor_map,
    }

    dest = build / "site-index.json"
    dest.write_text(json.dumps(index, indent=2, ensure_ascii=False), encoding="utf-8")
    print(
        f"  ✓ Generated site-index.json "
        f"({len(papers_out)} papers, {len(anchor_map)} anchors)"
    )


def copy_machine_readable_assets(
    build: Path,
    refs_data: dict[str, Any],
    anchor_map: dict[str, str],
    contents: dict[str, Any],
    link_map: dict[str, str],
) -> None:
    """
    Copy source-of-truth data files into _build/ as static endpoints,
    then generate site-index.json.

    Endpoints served:
      /references.json    — full reference database
      /anchors.yml        — section-to-URL anchor map
      /wdt-contents.yml   — paper/section hierarchy
      /references.bib     — BibTeX bibliography
      /site-index.json    — merged navigation index (generated)
    """
    assets = [
        (REFERENCES_JSON,                         build / "references.json"),
        (ROOT_DIR / "registry" / "anchors.yml",   build / "anchors.yml"),
        (ROOT_DIR / "registry" / "contents.yml",  build / "wdt-contents.yml"),
        (ROOT_DIR / "registry" / "references.bib", build / "references.bib"),
    ]
    for src, dst in assets:
        if src.exists():
            shutil.copy2(src, dst)
            print(f"  ✓ {src.name} → {dst.name}")
        else:
            print(f"  ! {src.name} not found — skipping")

    generate_site_index(build, refs_data, anchor_map, contents, link_map)
