"""
WDT site preprocessing pipeline.
Reads .md source files, processes them for HTML rendering, writes .qmd to _build/.
Run this before every `quarto render _build`.

Workflow:
  1. python build_anchors.py   (regenerate anchors.yml from wdt-contents.yml)
  2. python preprocess.py      (stage all papers into _build/)
  3. quarto render _build
"""

import os, re, shutil
from pathlib import Path
import yaml

# ── SET THIS TO YOUR SOURCE FOLDER ──────────────────────────────────────────
SOURCE_DIR = "source_md"   # <-- edit this line
BUILD_DIR  = "_build"
CROSSLINKS = "cross_links.yml"
ANCHORS    = "anchors.yml"
# ────────────────────────────────────────────────────────────────────────────

with open(CROSSLINKS, encoding="utf-8") as f:
    link_map = yaml.safe_load(f)

# Load anchor map if available (generated by build_anchors.py)
anchor_map = {}
if Path(ANCHORS).exists():
    with open(ANCHORS, encoding="utf-8") as f:
        anchor_map = yaml.safe_load(f) or {}
else:
    print(f"  ! {ANCHORS} not found — cross-references will link to page root only.")
    print(f"    Run: python build_anchors.py")

# Matches (WP), (VAL §3.7), (CORP.A §F.9), (GOV.B §A.1.3), etc.
# Group 1: shortcode   Group 2: section number (without §), optional
CROSSREF_RE = re.compile(
    r'\(([A-Z][A-Z0-9]*(?:\.[A-Z][A-Z0-9]*)?)(?:\s+§([\d.A-Za-z]+))?\)'
)

LATEX_STRIP = [
    r'\\newpage', r'\\medskip', r'\\bigskip', r'\\smallskip',
    r'\\tableofcontents', r'\\appendix', r'\\maketitle',
    r'\\begin\{center\}', r'\\end\{center\}',
    r'\\noindent', r'\\clearpage',
    r'\\vspace\*?\{[^}]+\}', r'\\hspace\*?\{[^}]+\}',
    r'\\setcounter\{[^}]+\}\{[^}]+\}',
]
LATEX_RE = re.compile('|'.join(LATEX_STRIP))

INTBIB_LINE_RE = re.compile(r'^\[([A-Z][A-Z0-9]*(?:\.[A-Z][A-Z0-9]*)?)\]\s+(.+)$')


def resolve_crossref(shortcode: str, section: str | None) -> str | None:
    """
    Return the URL for a cross-reference, or None if the shortcode is unknown.

    Resolution order:
      1. If section is given, look up PAPER§SECTION in anchor_map for a deep link.
      2. Fall back to page root from link_map.
      3. If shortcode unknown, return None (leave reference as plain text).
    """
    if shortcode not in link_map:
        return None

    if section:
        anchor_key = f"{shortcode}§{section}"
        if anchor_key in anchor_map:
            return anchor_map[anchor_key]
        # Section not found in anchor map — fall back to page root
        # (happens for papers not yet in wdt-contents.yml, or top-level numeric sections)

    return link_map[shortcode]


def convert_crossrefs(text: str) -> str:
    def replace(m):
        full      = m.group(0)          # e.g. "(GOV.B §A.1.3)"
        shortcode = m.group(1)          # e.g. "GOV.B"
        section   = m.group(2)          # e.g. "A.1.3" or None

        url = resolve_crossref(shortcode, section)
        if url is None:
            return full                  # unknown shortcode — leave as-is
        return f'[{full}]({url})'

    return CROSSREF_RE.sub(replace, text)


def convert_internal_bibliography(lines):
    result, in_block = [], False
    for line in lines:
        m = INTBIB_LINE_RE.match(line.rstrip())
        if m:
            if not in_block:
                result.append('\n::: {.internal-bibliography}\n')
                in_block = True
            code, rest = m.group(1), m.group(2)
            result.append(f'**[{code}]** {rest}\n')
        else:
            if in_block:
                result.append(':::\n')
                in_block = False
            result.append(line)
    if in_block:
        result.append(':::\n')
    return result


def process_file(src_path, dest_path):
    text = src_path.read_text(encoding="utf-8")
    text = LATEX_RE.sub('', text)
    text = convert_crossrefs(text)
    lines = convert_internal_bibliography(text.splitlines(keepends=True))
    text = ''.join(lines)
    dest_path.parent.mkdir(parents=True, exist_ok=True)
    dest_path.write_text(text, encoding="utf-8")
    print(f"  ✓ {src_path.name} → {dest_path.name}")


def main():
    build  = Path(BUILD_DIR)
    source = Path(SOURCE_DIR)

    if build.exists():
        shutil.rmtree(build, ignore_errors=True)
    build.mkdir(exist_ok=True)

    for fname in ["_quarto.yml", "styles.css", "wdt_references.bib", "index.qmd", "apa.csl"]:
        p = Path(fname)
        if p.exists():
            shutil.copy(p, build / fname)
        else:
            if fname != "wdt_references.bib":   # bib is optional until Stage 1.5
                print(f"  ! Missing: {fname}")

    registry_path = Path("paper_registry.yml")
    if not registry_path.exists():
        print("ERROR: paper_registry.yml not found.")
        return

    with open(registry_path, encoding="utf-8") as f:
        registry = yaml.safe_load(f)

    found, missing = 0, 0
    for entry in registry:
        shortcode   = entry["shortcode"]
        source_glob = entry["source_glob"]
        output_name = entry["output"]

        matches = sorted(source.glob(source_glob))
        if not matches:
            print(f"  – {shortcode}: no file found (skipped)")
            missing += 1
            continue
        if len(matches) > 1:
            print(f"  ! {shortcode}: multiple matches, using {matches[-1].name}")

        process_file(matches[-1], build / output_name)
        found += 1

    print(f"\nDone. {found} papers staged, {missing} not yet available.")
    print(f"Run: quarto render {BUILD_DIR}")


if __name__ == "__main__":
    main()
